const tapirs = [
    {
        category: "water tapir",
        price: 5,
        img: "https://ideas.ted.com/wp-content/uploads/sites/3/2015/11/tapir_4_daniel-zupanc.jpg",
        alt: "",
        inStock: true,
    },
    {
        category: "grass tapir",
        price: 5,
        img: "https://th.bing.com/th/id/OIP.hvt0IDWKDsydPYZ0BLbTWQHaFA?w=286&h=193&c=7&r=0&o=7&pid=1.7&rm=3",
        alt: "",
        inStock: true,
    },
    {
        category: "land tapir",
        price: 5,
        img: "https://th.bing.com/th/id/OIP.UAeh2jRhxY2ouHOyOoRqhgHaEj?w=313&h=193&c=7&r=0&o=7&pid=1.7&rm=3",
        alt: "",
        inStock: true,
    },
    {
        category: "dirt tapir",
        price: 5,
        img: "https://imgs.mongabay.com/wp-content/uploads/sites/20/2019/01/14064748/animals_00884-762x512.jpg",
        alt: "",
        inStock: true,
    },
    {
        category: "land tapir",
        price: 5,
        img: "https://tse1.mm.bing.net/th/id/OIP.V9aeKEmWPjvZHdMFwy9ixQHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "",
        inStock: true,
    },
    {
        category: "land tapir",
        price: 5,
        img: "https://tse2.mm.bing.net/th/id/OIP.MBxRql-4XGYCLZjZgUAVoQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "",
        inStock: true,
    },
    {
        category: "grass tapir",
        price: 5,
        img: "https://th.bing.com/th/id/R.422d88ed33afff59dd4335534d9e5d96?rik=CYBya9UyEbnjog&pid=ImgRaw&r=0",
        alt: "",
        inStock: true,
    },
    {
        category: "grass tapir",
        price: 5,
        img: "https://www.worldatlas.com/r/w1200/upload/07/81/69/shutterstock-534346312.jpg",
        alt: "",
        inStock: true,
    },
    {
        category: "baby tapir",
        price: 5,
        img: "https://animals.sandiegozoo.org/sites/default/files/inline-images/tapir_baby_animals.jpg",
        alt: "",
        inStock: true,
    },
    {
        category: "water tapir",
        price: 5,
        img: "https://th.bing.com/th/id/R.b5722c2630fbe139a48024dd01a8aaed?rik=b4TSrEFqVwpfJw&pid=ImgRaw&r=0",
        alt: "",
        inStock: true,
    },
    {
        category: "land tapir",
        price: 5,
        img: "https://th.bing.com/th/id/R.de23c02c473cff5749d5ba12da563451?rik=OeGFz8FrehMo9Q&pid=ImgRaw&r=0",
        alt: "",
        inStock: true,
    },
    {
        category: "land tapir",
        price: 5,
        img: "https://tse2.mm.bing.net/th/id/OIP.mIeYTHwhEXEcb-lRNj-hvAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
    {
        category: "",
        price: 5,
        img: "",
        alt: "",
        inStock: true,
    },
]

tapirs.forEach((tapirs) => console.log(tapirs.category))
